// Auto-generated by TestFly Locator Engine. DO NOT EDIT DIRECTLY.

declare global {
  namespace TestFly {
    interface LocatorMap {
      'login.username_field': true;
      'login.password_field': true;
      'login.login_button': true;
      'login.error_message': true;
      'products.title': true;
      'products.inventory_item': true;
      'products.add_to_cart_btn': true;
      'products.cart_badge': true;
    }

    type LocatorPath = keyof LocatorMap;
  }
}

export {};
