import fs from 'fs';
import path from 'path';
import { ParsedLocatorItem } from './types';
import { LocatorParser } from './LocatorParser';

export class LocatorTypeGen {
  /**
   * Generate TypeScript declaration code from parsed locator items
   */
  static generateDts(items: ParsedLocatorItem[]): string {
    const keys = items.map((i) => `'${i.fullKey}'`);
    const unionType = keys.length > 0 ? keys.join('\n  | ') : 'string';

    const lines: string[] = [
      '// Auto-generated by TestFly Playwright Locator TypeGen. DO NOT EDIT.',
      '',
      'declare global {',
      '  namespace TestFly {',
      `    export type LocatorPath = \n  | ${unionType};`,
      '  }',
      '}',
      '',
      `export type TestFlyLocatorKey = \n  | ${unionType};`,
      '',
      'export interface GeneratedLocatorRegistry {',
    ];

    // Group by page
    const byPage: Record<string, string[]> = {};
    for (const item of items) {
      if (!byPage[item.page]) byPage[item.page] = [];
      byPage[item.page].push(item.name);
    }

    for (const [page, names] of Object.entries(byPage)) {
      lines.push(`  ${page}: {`);
      for (const name of names) {
        lines.push(`    ${name}: '${page}.${name}';`);
      }
      lines.push('  };');
    }

    lines.push('}');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Scan locators directory and write type declaration file
   */
  static generateToFile(locatorsDir: string, outputFile: string): { count: number; outputPath: string } {
    const items = LocatorParser.parseDirectory(locatorsDir);
    const dtsContent = this.generateDts(items);

    const outDir = path.dirname(outputFile);
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }

    fs.writeFileSync(outputFile, dtsContent, 'utf8');
    return {
      count: items.length,
      outputPath: outputFile,
    };
  }
}
