// Auto-generated by TestFly Playwright Locator TypeGen. DO NOT EDIT.

declare global {
  namespace TestFly {
    export type LocatorPath = 
  | 'login.username_input'
  | 'login.password_input'
  | 'login.login_btn'
  | 'login.cart_icon';
  }
}

export type TestFlyLocatorKey = 
  | 'login.username_input'
  | 'login.password_input'
  | 'login.login_btn'
  | 'login.cart_icon';

export interface GeneratedLocatorRegistry {
  login: {
    username_input: 'login.username_input';
    password_input: 'login.password_input';
    login_btn: 'login.login_btn';
    cart_icon: 'login.cart_icon';
  };
}
