// Auto-generated by TestFly Locator Engine. DO NOT EDIT DIRECTLY.

declare global {
  namespace TestFly {
    interface LocatorMap {
      'mobile_app.welcome_title': true;
      'mobile_app.onboarding_carousel': true;
      'mobile_app.get_started_btn': true;
      'mobile_app.login_sheet': true;
    }

    type LocatorPath = keyof LocatorMap;
  }
}

export {};
