import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    bdd: 'src/bdd.ts',
    'config/index': 'src/config/index.ts',
    'fixtures/index': 'src/fixtures/index.ts',
    'client/index': 'src/client/index.ts',
    'db/index': 'src/db/index.ts',
    'mail/index': 'src/mail/index.ts',
    'steps/index': 'src/steps/index.ts',
    'a11y/index': 'src/a11y/index.ts',
    'mock/index': 'src/mock/index.ts',
    'generator/index': 'src/generator/index.ts',
    'notifications/index': 'src/notifications/index.ts',
    'performance/index': 'src/performance/index.ts',
    'scanner/index': 'src/scanner/index.ts',
    'doctor/index': 'src/doctor/index.ts',
    'visual/index': 'src/visual/index.ts',
    'faker/index': 'src/faker/index.ts',
    'mobile/index': 'src/mobile/index.ts',
    'context/index': 'src/context/index.ts',
    'cli/bin': 'src/cli/bin.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  shims: true,
  external: ['@playwright/test', 'playwright-bdd'],
});
